# Generated by Django 4.2.28 on 2026-02-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(help_text='Short one-line summary', max_length=300)),
                ('problem', models.TextField(help_text='Problem description')),
                ('solution', models.TextField(help_text='Solution approach')),
                ('tech_stack', models.CharField(help_text='Comma-separated e.g. Django, PostgreSQL, Celery', max_length=500)),
                ('key_results', models.TextField(help_text='Key results / impact (one per line or short paragraphs)')),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True, help_text='Optional live demo URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_studies/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
